/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cd.enquiry.service;

import org.junit.Test;

import com.cd.enquiry.msvc.EnquiryServiceMain;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        EnquiryServiceMain classUnderTest = new EnquiryServiceMain();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
